spring:
  application:
    name: eureka-server

server:
  port: 1002

eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
          defaultZone: http://peer2:1003/eureka/




