spring:
  application:
    name: eureka-consumer
server:
  port: 3001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
#      defaultZone: http://peer1:1002/eureka/,http://peer2:1003/eureka/

